### ISSUE TITLE
Instructor Feedback Week 3

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [cgreger/GW2Auxiliary#1]
I'm impressed with the quantity and quality of work so far!

You mentioned Lucene for your suggested search functionality. You might also consider [Hibernate Search](http://hibernate.org/search/). I have not used either one, so I can't make a good recommendation, but I think it could be valuable to explore the options (maybe you already did this!).

Looking forward to your progress on this!

**Comment by cgreger** [comment]
Hi Paula,

I looked at the documentation a little bit but I'm unsure if Hibernate Search is able to provide suggestive searches. I will look into it a bit more before I decide.

Thank you for the suggestion and feedback! I am very excited for this project!
