### ISSUE TITLE
Feedback (Shea Prewett)

### ISSUE THREAD

**Issue by SheaPrewett** [cgreger/GW2Auxiliary#2]
# Design/Code Review 1

#### Reviewer: Shea Prewett

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Problem Statement**|Does it exist?| Yes|
| |Does the problem statement accurately describe project purpose?| Yes|
| |Is the problem statement professional? Think of prospective employers viewing this as part of the developer's portfolio.| Yes, detailed and well-written.|
| |What is good?| Explains the problem well, as well as proposed solutions.|
| |What could be improved?| Nothing comes to mind, other than it being a bit ambitious.|
|**Design Documentation**|Does it exist?| Yes|
| |Is the navigation/flow through the application logical and easy to use?| Seems so.|
| |Is the order in which the fields are displayed and form fields entered logical and easy to use?| Yes.|
| |What data is missing?| Nothing comes to mind.|
| |Is there data that is not used?| Nothing comes to mind.|
| |What is good?| Makes sense, looks good, covers bases. I like the inclusion of mobile design.|
| |What could be improved?| |
|**Data model**|Does it exist?| Yes|
| |Is everything on the screens represented in the model?| Yes|
| |Does the model represent good database design? | Yes|
| |What is good?| Clear design|
| |What could be better?| Not sure if more data is needed for items.|
|**Additional design documents**| | |
|**Application structure in IntelliJ**|Does it exist?| Yes|
| |Is the structure correct for a Maven project?| Yes|
| |Are packages and classes appropriately named?   | Yes|
| |Other comments/notes?| |
|**JSPs**|Do they exist?| Yes.|
| |Is templating used (for example, header.jsp, footer.jsp, etc.)?| Not yet|
| |Is there business logic mixed in the JSPs?| No|
| |CSS?| Not yet|
| |Other comments/notes?| |
|**Entities/DAOs/Controllers**|Do they exist?| Yes|
|**Java code quality**|Are methods single-purpose?| Seems so|
| |Are classes appropriately-sized classes (no monster classes)?| Seems so|
| |Are the same lines of code repeated at all?| Only some in DAO, seems essential| 
| |Do any classes perform very similar functions that could be candidates for super/subclass relationships?| None that I see|
| |Are any values hard-coded that should be in a properties file?| None that I see|
| |Are variable names descriptive?| Seems so|
| |Are there many branches or loops that could be simplified or broken up into smaller methods?| None that I see|
| |Do the DAOs use Hibernate? No hard-coded sql!| Yes|
| |Other comments/notes?| |
|**Logging**|Has log4J been added?| Yes|
| |Are there logging statements in the code?| Yes|
| |Are appropriate logging levels used? Info, debug, error, for example.| Yes|
| |Are there any System.out.printlns in the code?| No|
| |Other comments/notes?| |
|**Unit Tests**|Do they exist?| Yes|
| |Do the tests pass?| They did, some recent changes broke it.|
| |What is the current code coverage?| 55% for DAO's|
| |Is each test truly a unit test or are they functional tests?| Unit |
| |Other comments/notes?| |
|**Web Service/API integration**|Has a web service/api been selected? | Yes|
| |What web services/apis might work well with this application?| Arena.net API|
|**Independent research topic**| Has a topic been selected?| Yes|
| |What topic/s might fit well in this application?| Apache Lucene|

**Comment by pawaitemadisoncollege** [comment]
Please update this for prettier formatting - adding a space between the || on the lefthand side should do it.
