### ISSUE TITLE
Instructor Feedback Week 3 Exercise - Hibernate

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [cgreger/GW2Auxiliary#3]
Looks like you have a great start! Really good work overall!

- [x] I like that you are using @BeforeClass to set up some test records. What do you think about cleaning those up afterwards? 
- [x] Great job using a test database. I think this is much cleaner!
- [x] What are your thoughts on more thoroughly [testing the fields in addition to the password](https://github.com/cgreger/GW2Auxiliary/blob/master/src/test/java/com/cgreger/persistence/UserDAOTest.java#L91)?

**Comment by cgreger** [comment]
Thanks!
\- On my test database I have the records automatically cleaned by putting this into my test db's hibernate properties file:

`<property name="hibernate.hbm2ddl.auto">create-drop</property>`

It creates a brand new db from the original db's schema when the SessionFactory is instantiated, and then when the SessionFactory is closed (At this point when the tests are finished running), the entire db is dropped. 

This ensures that I will always have the same database schema at the beginning of my tests, which allows me to easily add whatever data I need in the @BeforeClass method.

\- I agree! Definitely made testing a lot easier once I figured out how to do it.
\- That sounds like a good idea, I will try implementing more tests for the individual password fields.

**Comment by pawaitemadisoncollege** [comment]
Hey, that: <property name="hibernate.hbm2ddl.auto">create-drop</property> is a great way to handle this. You should share this as a tip in help! Way to go!

On Feb 11, 2017, at 12:20 PM, Chelsea Greger <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks!
- On my test database I have the records automatically cleaned by putting this into my test db's hibernate properties file:

<property name="hibernate.hbm2ddl.auto">create-drop</property>

It creates a brand new db from the original db's schema when the SessionFactory is instantiated, and then when the SessionFactory is closed (At this point when the tests are finished running), the entire db is dropped.

This ensures that I will always have the same database schema at the beginning of my tests, which allows me to easily add whatever data I need in the @BeforeClass method.

- I agree! Definitely made testing a lot easier once I figured out how to do it.
- That sounds like a good idea, I will try implementing more tests for the individual password fields.
